Repository codaxy/cxjs, pull requests merged in 2022-03, with the labels that each got.

#933 tab change confirmation
  packages/cx/src/ui/app/History.d.ts
  packages/cx/src/ui/app/History.js
  packages/cx/src/widgets/nav/Tab.js
Labels: feature request

#936 double resizer element for column resizing
  packages/cx/src/widgets/grid/Grid.js
  packages/cx/src/widgets/grid/Grid.scss
Labels: enhancement

#941 Docs/fiddle button
  docs/components/CodeSnippet.js
  docs/components/CodeSnippet.scss
Labels: documentation

#944 Update TreeAdapter.js
  packages/cx/src/ui/adapter/TreeAdapter.js
Labels: bug

#946 show viewText if set, for checkbox in view mode
  docs/content/widgets/FieldGroups.js
  docs/content/widgets/configs/Checkbox.js
  packages/cx/src/widgets/form/Checkbox.d.ts
  packages/cx/src/widgets/form/Checkbox.js
Labels: feature request

#947 check previous header resizable flag when rendering resizer for previ…
  packages/cx/src/widgets/grid/Grid.js
Labels: bug
