Repository codaxy/cxjs, pull requests merged in 2022-02, with the labels that each got.

#914 add lookup all options selection on ctrl + a key combination
  docs/content/widgets/LookupFields.js
  docs/content/widgets/configs/LookupField.js
  packages/cx/src/widgets/form/LookupField.d.ts
  packages/cx/src/widgets/form/LookupField.js
Labels: feature request

#916 fix lookup field selection
  packages/cx/src/widgets/form/LookupField.js
Labels: bug

#928 Remove incorrect description from windows
  docs/content/widgets/configs/Window.js
Labels: enhancement, documentation

#927 Add Pie Labels component
  .DS_Store
  docs/app/DocsNav.js
  docs/content/charts/PieLabels.js
  docs/content/charts/configs/PieLabels.js
  docs/content/charts/index.js
  litmus/features/charts/pie/PieLabels.js
  litmus/features/charts/pie/labels.js
  litmus/index.js
  packages/.DS_Store
  packages/create-cx-app/index.js
  packages/cx-cli/index.js
  packages/cx/.DS_Store
  packages/cx/src/.DS_Store
  packages/cx/src/charts/PieLabel.d.ts
  packages/cx/src/charts/PieLabel.js
  packages/cx/src/charts/PieLabelsContainer.d.ts
  packages/cx/src/charts/PieLabelsContainer.js
  packages/cx/src/charts/index.d.ts
  packages/cx/src/charts/index.js
Labels: feature request

#930 add cellEditable grid onBeforeCellEdit callback
  packages/cx/src/widgets/grid/Grid.d.ts
  packages/cx/src/widgets/grid/Grid.js
Labels: feature request

#929 add missing .ts def for unfocusElement
  packages/cx/src/ui/FocusManager.d.ts
Labels: type definitions
