Repository codaxy/cxjs, pull requests merged in 2022-04, with the labels that each got.

#952 calculate width according to correct column when double clicking resi…
  packages/cx/src/widgets/grid/Grid.js
Labels: bug

#953 modify comparer to show null values on the bottom
  packages/cx/src/data/comparer.js
Labels: enhancement

#958 Fix lookup field custom bindings wrong link
  docs/content/widgets/configs/LookupField.js
Labels: documentation
