Repository codaxy/cxjs, pull requests merged in 2024-02, with the labels that each got.

#1151 Small clean up
  docs/content/concepts/Charts.js
  docs/content/concepts/DataBinding.js
  docs/content/concepts/InnerLayouts.js
  docs/content/concepts/Widgets.js
Labels: enhancement

#1141 Add filtering example
  docs/app/DocsNav.js
  docs/content/examples/grid/MultipleSelection.js
  docs/content/examples/grid/SearchingAndFiltering.js
  docs/content/examples/grid/TreeGrid.js
  docs/content/examples/grid/index.js
  docs/content/widgets/Grids.js
  docs/content/widgets/TreeGrid.js
  docs/content/widgets/configs/Grid.js
Labels: documentation

#1153 Document onParseInput
  docs/content/widgets/DateTimeFields.js
  docs/content/widgets/configs/DateField.js
Labels: documentation

#1152 Update number and currency formatting flags
  docs/content/concepts/Formatting.js
  docs/content/concepts/configs/DataProxy.js
  docs/content/concepts/configs/Formatting.js
Labels: enhancement, documentation

#1158 Document registerKeyboardShortcut
  docs/app/DocsNav.js
  docs/content/concepts/KeyboardShortcuts.js
  docs/content/concepts/index.js
  packages/cx/src/ui/keyboardShortcuts.js
Labels: documentation

#1163 Document Validator & ValidationError
  docs/app/DocsNav.js
  docs/content/widgets/ValidationGroups.js
  docs/content/widgets/Validators.js
  docs/content/widgets/Validators.scss
  docs/content/widgets/configs/ValidationGroup.js
  docs/content/widgets/configs/Validator.js
Labels: enhancement, documentation

#1162 Document SimpleSelection
  docs/content/concepts/Selections.js
  packages/cx/src/ui/selection/KeySelection.d.ts
  packages/cx/src/ui/selection/PropertySelection.d.ts
  packages/cx/src/ui/selection/PropertySelection.js
  packages/cx/src/ui/selection/Selection.d.ts
Labels: documentation

#1140 Apply changes before unmounting focused fields
  packages/cx/src/widgets/form/ColorField.js
  packages/cx/src/widgets/form/DateTimeField.js
  packages/cx/src/widgets/form/MonthField.js
  packages/cx/src/widgets/form/NumberField.js
  packages/cx/src/widgets/form/TextArea.js
  packages/cx/src/widgets/form/TextField.js
Labels: enhancement

#1161 Document Cx component and injecting Cx widgets into React
  docs/app/DocsNav.js
  docs/content/concepts/CxComponent.js
  docs/content/concepts/configs/CxComponent.js
  docs/content/concepts/index.js
  packages/cx/src/ui/Cx.d.ts
  packages/cx/src/ui/app/startAppLoop.js
Labels: documentation

#1160 Add guide for creating new components
  docs/app/DocsNav.js
  docs/content/concepts/CreatingComponents.js
  docs/content/concepts/index.js
  docs/content/widgets/Checkboxes.js
Labels: documentation
