Repository codaxy/cxjs, pull requests merged in 2024-01, with the labels that each got.

#1122 Document dataAdapter property
  docs/app/DocsNav.js
  docs/content/examples/grid/TreeGrid.js
  docs/content/widgets/Grids.js
  docs/content/widgets/TreeGrid.js
  docs/content/widgets/configs/Grid.js
  docs/content/widgets/configs/TreeNode.js
Labels: enhancement, documentation

#1124 add grid onRef callback
  docs/content/examples/grid/ColumnResizing.js
  docs/content/widgets/configs/Grid.js
  packages/cx/src/widgets/grid/Grid.d.ts
  packages/cx/src/widgets/grid/Grid.js
Labels: feature request

#1125 Fix a typo
  fiddle/app/routes/default/Header.js
Labels: enhancement

#1121 Update localization documentation
  docs/content/charts/BarGraphs.js
  docs/content/charts/Bars.js
  docs/content/charts/ColorMap.js
  docs/content/charts/ColumnGraphs.js
  docs/content/charts/Columns.js
  docs/content/charts/Legend.js
  docs/content/charts/LineGraphs.js
  docs/content/charts/Markers.js
  docs/content/charts/PieCharts.js
  docs/content/charts/PieLabels.js
  docs/content/charts/Ranges.js
  docs/content/charts/TimeAxis.js
  docs/content/charts/configs/ColumnBarGraphBase.js
  docs/content/concepts/Localization.js
  docs/content/concepts/Selections.js
  docs/content/widgets/Tooltips.js
Labels: enhancement, documentation

#1126 Create separate pages for data views
  README.md
  docs/app/DocsNav.js
  docs/content/concepts/DataBinding.js
  docs/content/concepts/DataProxy.js
  docs/content/concepts/DataViews.js
  docs/content/concepts/Repeater.js
  docs/content/concepts/Rescope.js
  docs/content/concepts/Router.js
  docs/content/concepts/Sandbox.js
  docs/content/concepts/Store.js
  docs/content/concepts/Widgets.js
  docs/content/concepts/configs/DataProxy.js
  docs/content/concepts/index.js
  docs/content/data-views/DataViews.js
  docs/content/data-views/Repeater.js
  docs/content/data-views/index.js
  docs/content/examples/grid/ColumnReordering.js
  docs/content/examples/grid/DynamicColumns.js
  docs/content/examples/grid/FormEdit.js
  docs/content/examples/grid/Grouping.js
  docs/content/examples/grid/RowEditing.js
  docs/content/examples/grid/RowExpanding.js
  docs/content/examples/grid/TreeGrid.js
  docs/content/intro/GettingStarted.js
  docs/content/intro/Jsx.js
  docs/content/svg/NonOverlappingRects.js
  docs/content/widgets/Grids.js
  docs/content/widgets/Lists.js
  docs/content/widgets/configs/Repeater.js
  docs/content/widgets/configs/Rescope.js
  docs/content/widgets/configs/Sandbox.js
  litmus/bugs/search.js
  packages/cx/src/ui/DataProxy.d.ts
  packages/cx/src/ui/DataProxy.js
  packages/cx/src/ui/Rescope.js
Labels: bug, documentation, undocumented

#1128 Document new culture methods
  docs/content/concepts/Localization.js
Labels: documentation

#1134 Display key Culture methods on top
  docs/content/concepts/Localization.js
Labels: enhancement, documentation

#1130 Create page for Row Drag & Drop
  docs/app/DocsNav.js
  docs/content/concepts/DragAndDrop.js
  docs/content/examples/grid/RowDragAndDrop.js
  docs/content/examples/grid/RowDragAndDrop.scss
  docs/content/examples/grid/index.js
  docs/content/widgets/Grids.js
  docs/content/widgets/configs/GridDragAndDrop.js
  packages/cx/src/widgets/grid/Grid.d.ts
Labels: documentation

#1132 Update Store docs
  docs/content/concepts/Store.js
  packages/cx/src/data/ops/updateTree.js
  packages/cx/src/data/ops/updateTree.spec.js
Labels: enhancement, documentation

#1131 Refresh Step-by-step docs
  docs/content/concepts/Formatting.js
  docs/content/intro/StepByStep.js
Labels: enhancement, documentation

#1135 Add copy button to CodeSnippet
  docs/components/CodeSnippet.js
  docs/components/CodeSnippet.scss
  docs/components/ConfigTable.js
  docs/components/ImportPath.js
  docs/content/charts/Legend.js
  docs/content/charts/ValueAtFinder.js
  docs/content/concepts/Css.js
  docs/content/concepts/Formatting.js
  docs/content/concepts/ImmerJsIntegration.js
  docs/content/concepts/InnerLayouts.js
  docs/content/concepts/Localization.js
  docs/content/concepts/OuterLayouts.js
  docs/content/concepts/Rescope.js
  docs/content/concepts/Router.js
  docs/content/concepts/TypedModels.js
  docs/content/examples/grid/ColumnReordering.js
  docs/content/examples/grid/DynamicColumns.js
  docs/content/examples/grid/FixedColumns.js
  docs/content/examples/grid/Grouping.js
  docs/content/intro/BreakingChanges.js
  docs/content/intro/CommandLine.js
  docs/content/intro/GettingStarted.js
  docs/content/intro/Jsx.js
  docs/content/intro/NpmPackages.js
  docs/content/intro/StepByStep.js
  docs/content/intro/Welcome.js
  docs/content/intro/WelcomeExample.js
  docs/content/widgets/Buttons.js
  docs/content/widgets/FlexBox.js
Labels: enhancement

#1139 Reorder code in chronological order
  docs/content/concepts/ImmerJsIntegration.js
  docs/content/concepts/OuterLayouts.js
Labels: enhancement

#1138 Add localization example
  docs/content/concepts/Localization.js
  packages/cx/locale/de-de.js
  packages/cx/locale/en-us.js
  packages/cx/locale/es-es.js
  packages/cx/locale/fr-fr.js
  packages/cx/locale/nl-nl.js
  packages/cx/locale/pt-pt.js
  packages/cx/locale/sr-latn-ba.js
  packages/cx/src/ui/Culture.d.ts
  packages/cx/src/ui/Localization.js
  packages/cx/src/ui/Text.js
Labels: documentation

#1149 Add usage of fmt to the example
  docs/content/concepts/Formatting.js
Labels: documentation

#1150 Document new flags
  docs/content/concepts/Formatting.js
Labels: documentation
